In [1]:
import numpy as np

In [2]:
n = 2

In [3]:
2 ** 4

16

In [4]:
import sys

In [5]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [9]:
a = np.array([5,6,7,8])

In [10]:
a[0], a[2]

(5, 7)

In [11]:
list1 = [1,2,3,4]

In [12]:
print(list1)

[1, 2, 3, 4]


In [13]:
arr_list1 = np.array(list1)

In [14]:
print(arr_list1)

[1 2 3 4]


In [15]:
print(type(arr_list1))

<class 'numpy.ndarray'>


In [16]:
list1 = [1,2,3,4]
list2 = [5,6,7,8]

In [17]:
arr_list2d = np.array([list1,list2])

In [18]:
print(arr_list2d)

[[1 2 3 4]
 [5 6 7 8]]


In [19]:
print(type(arr_list2d))

<class 'numpy.ndarray'>


In [20]:
print(arr_list2d.ndim)

2
